/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ViolationService } from "../violation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ViolationCreateInput } from "./ViolationCreateInput";
import { Violation } from "./Violation";
import { ViolationFindManyArgs } from "./ViolationFindManyArgs";
import { ViolationWhereUniqueInput } from "./ViolationWhereUniqueInput";
import { ViolationUpdateInput } from "./ViolationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ViolationControllerBase {
  constructor(
    protected readonly service: ViolationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Violation })
  @nestAccessControl.UseRoles({
    resource: "Violation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createViolation(
    @common.Body() data: ViolationCreateInput
  ): Promise<Violation> {
    return await this.service.createViolation({
      data: {
        ...data,

        session: data.session
          ? {
              connect: data.session,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,

        session: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Violation] })
  @ApiNestedQuery(ViolationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Violation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async violations(@common.Req() request: Request): Promise<Violation[]> {
    const args = plainToClass(ViolationFindManyArgs, request.query);
    return this.service.violations({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,

        session: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Violation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Violation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async violation(
    @common.Param() params: ViolationWhereUniqueInput
  ): Promise<Violation | null> {
    const result = await this.service.violation({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,

        session: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Violation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Violation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateViolation(
    @common.Param() params: ViolationWhereUniqueInput,
    @common.Body() data: ViolationUpdateInput
  ): Promise<Violation | null> {
    try {
      return await this.service.updateViolation({
        where: params,
        data: {
          ...data,

          session: data.session
            ? {
                connect: data.session,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,

          session: {
            select: {
              id: true,
            },
          },

          timestamp: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Violation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Violation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteViolation(
    @common.Param() params: ViolationWhereUniqueInput
  ): Promise<Violation | null> {
    try {
      return await this.service.deleteViolation({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,

          session: {
            select: {
              id: true,
            },
          },

          timestamp: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
